### PR TITLE
Add DHT info into GetNeighbor API

### PR DESCRIPTION
**Pull request by gdmmx**
Signed-off-by: gdmmx <gdmmx@163.com>

### Proposed changes in this pull request
Add DHT info into GetNeighbor API

### Type (put an `x` where ever applicable)
- [ ] Bug fix: Link to the issue
- [x] Feature (Non-breaking change)
- [ ] Feature (Breaking change)
- [ ] Documentation Improvement

### Checklist
Please put an `x` against the checkboxes. Write a small comment explaining if its `N/A` (not applicable)

- [x] Read the [CONTRIBUTION guidelines](https://github.com/nknorg/nkn#contributing).
- [x] All the tests are passing after the introduction of new changes.
- [ ] Added tests respective to the part of code I have written.
- [ ] Added proper documentation where ever applicable (in code and README.md).
- [x] Code has been written according to [NKN-Golang-Style-Guide](https://github.com/nknorg/nkn/wiki/NKN-Golang-Style-Guide)

### Extra information
Any extra information related to this pull request.

### CODE REVIEW

**Comment by NoelBright** [comment]
looks good to me.

**Comment by yilunzhang** [comment]
@gdmmx Do you plan to add DHT topology info to the API before merge?

**Comment by gdmmx** [comment]
@yilunzhang Successors & Predecessors info not suitable for getNeighbor API response. I plan put these info resp to original getChordRingInfo API. It should be delivered in another commit.

**Comment by yilunzhang** [comment]
Then looks good to me.

**Pull request merged**
