### PR TITLE
Introduce ci

### PR DESCRIPTION
**Pull request by abebeos**
### Proposed changes in this pull request
see #890

### Type (put an `x` where ever applicable)
- Feature (Non-breaking change)

### Checklist

> All the tests are passing after the introduction of new changes.

The test-system is not active, this PR is about activating the tests within githubs CI

### CI Run in Fork

https://github.com/abebeos/nkn/actions/runs/3980307585/jobs/6823295928#step:5:86

### CODE REVIEW

**Comment by bufrr** [comment]
I think maybe we should fix this testcase rather than skip it. 
Feel free if you want to make a new PR to resolve this error, or I can do either

**Comment by abebeos** [comment]
> or I can do either

would prefer if you can take a look (I want to avoid at this point going into too much code).

Note that merging with the 3 skipped tests is non-critical anyways, and strictly speaking, the way to go (Task A: activate CI, Task B: polish the test-suite, which can take longer)

**Comment by abebeos** [comment]
Please, if possible, merge this into branch "introduce-ci" for further refinement on the original repo, just to be sure.

**Review by yilunzhang — APPROVED** [review]
Looks good to me

**Comment by yilunzhang** [comment]
merged into `introduce-ci` branch as you suggested

**Pull request merged**
