### PR TITLE
Query self external IP & chordID via RPC to seedList, instead of ipify

### PR DESCRIPTION
**Pull request by gdmmx**
### Proposed changes in this pull request
Currently, nknd was informed self external IP by centralized service —— ipify.
For more decentralized, query self external IP & chordID via RPC to seedList, instead of ipify.

### Type (put an `x` where ever applicable)
- [ ] Bug fix: Link to the issue
- [ ] Feature (Non-breaking change)
- [x] Feature (Breaking change)
- [ ] Documentation Improvement

### Checklist
Please put an `x` against the checkboxes. Write a small comment explaining if its `N/A` (not applicable)

- [x] Read the [CONTRIBUTION guidelines](https://github.com/nknorg/nkn#contributing).
- [x] All the tests are passing after the introduction of new changes.
- [ ] Added tests respective to the part of code I have written.
- [ ] Added proper documentation where ever applicable (in code and README.md).
- [x] Code has been written according to [NKN-Golang-Style-Guide](https://github.com/nknorg/nkn/wiki/NKN-Golang-Style-Guide)

### Extra information
Any extra information related to this pull request.

### CODE REVIEW

**Comment by yilunzhang** [comment]
This PR seems to include #463 ?

**Comment by gdmmx** [comment]
@yilunzhang You are right. I missed handle the scene about create mode in non-local cluster.
I will append a commit for fix it.

**Comment by yilunzhang** [comment]
This PR is not updated as #463 yet

**Comment by yilunzhang** [comment]
AskMyID should be renamed to AskMyIP

**Pull request merged**
